name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: C# Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build ./ApolloRoboto.Commander/ApolloRoboto.Commander.csproj
    - name: Test
      run: dotnet test ./ApolloRoboto.Commander.Tests/ApolloRoboto.Commander.Tests.csproj --logger:"trx;LogFileName=${{ github.workspace }}/TestsResults;"
    - name: Upload Tests Results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: 'Test Run'
        path: ${{ github.workspace }}/TestsResults

  publish:
    name: C# Publish to Nuget
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Packing
        run: dotnet pack ./ApolloRoboto.Commander/ApolloRoboto.Commander.csproj
      - name: Nuget Pushing
        run: |
          dotnet nuget push \
          ./ApolloRoboto.Commander/bin/Debug/ApolloRoboto.Commander.*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json