name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build .\ARCommander\ARCommander.csproj
    - name: Test
      run: dotnet test .\ARCommander.Tests\ARCommander.Tests.csproj --verbosity normal
