name: Publish

on:
  workflow_dispatch:

jobs:

  publish:
    name: Publish to Nuget
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Packing
        run: dotnet pack ./Commander/Commander.csproj

      - name: Nuget Pushing
        run: |
          dotnet nuget push \
          ./Commander/bin/Debug/Commander.*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
